import React, { createContext, useContext, useReducer } from "react";
import { Button } from "./components/Button";

const CreateEditRoutes = () => {
  const [state, dispatch] = useContext(CreateRouteContext);
  return (
    <div>
      <div>Create and edit routes</div>
      {state ? (
        <div>
          <div>Creating route {state.routeName}</div>
          <div>Current stops:</div>
          <div>
            {state.stops.map((stop) => (
              <div key={stop.stopId}>{stop.stopId}</div>
            ))}
          </div>
          <div
            css={{
              display: "flex",
              gap: "4px",
            }}
          >
            <Button
              onClick={() => {
                dispatch({ type: "finish" });
              }}
            >
              Finish route
            </Button>
            <Button
              onClick={() => {
                dispatch({ type: "cancel" });
              }}
            >
              Cancel route
            </Button>
          </div>
        </div>
      ) : (
        <div>
          <Button
            onClick={() => {
              dispatch({ type: "start" });
            }}
          >
            Start route
          </Button>
        </div>
      )}
    </div>
  );
};

type CreatedRoute = {
  // todo: align with what the app has
  stops: {
    stopId: string;
  }[];
  routeName: string;
};

export function createRouteReducer(
  state: CreateRouteState,
  action: { type: "start" | "finish" | "cancel" | "add-stop" }
): CreatedRoute | undefined {
  switch (action.type) {
    case "start": {
      return {
        stops: [],
        routeName: "Autogenerated route 1",
      };
    }
    case "add-stop": {
      if (!state) {
        return undefined;
      }
      const stops = [...state.stops];
      stops.push({ stopId: "jieufahsdfo" });
      return {
        ...state,
        stops,
      };
    }
    case "finish": {
      // use finished value
      return undefined;
    }
    case "cancel": {
      return undefined;
    }
  }
}

type CreateRouteState = CreatedRoute | undefined;

const CreateRouteContext =
  createContext<[CreateRouteState, React.Dispatch<{ type: string }>]>(
    undefined
  );

export { CreateEditRoutes, CreateRouteContext };
